spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092

ms:
  product:
    host: http://localhost:8082
  customer:
    host: http://localhost:8082
  shipping:
    host: http://localhost:8082
  payment:
    host: http://localhost:9090