spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}

ms:
  product:
    host: http://localhost:8082
  customer:
    host: http://localhost:8082
  shipping:
    host: http://localhost:8082
  payment:
    host: http://localhost:9090
