spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

ms:
  product:
    host: ${MS_PRODUCT_HOST}
  customer:
    host: ${MS_CUSTOMER_HOST}
  shipping:
    host: ${MS_SHIPPING_HOST}
  payment:
    host: ${MS_PAYMENT_HOST}

server:
  port: 8091