spring:
  application:
    name: ms-order
  sql:
    init:
      mode: always
  jpa:
    show: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
    org.apache.kafka: ERROR

kafka:
  topics:
    created-order: created-order-topic
    pending-payment: pending-payment-topic
    processed-order: processed-order-topic

server:
  port: 8091
