spring:
  application:
    name: ms-order
  sql:
    init:
      mode: always

  jpa:
    show: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8091

logging:
  level:
    root: INFO

kafka:
  topics:
    created-order: created-order-topic
    pending-payment: pending-payment-topic
