spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9092

ms:
  product:
    host: http://localhost:8093
  customer:
    host: http://localhost:8092
  shipping:
    host: http://localhost:8090
  payment:
    host: http://localhost:9090