name: order-management

services:
  ms-order-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - order-management-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ms-order-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - ms-order-zookeeper
    ports:
      - "9092:9092"
    networks:
      - order-management-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ms-order-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ms-order-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ms-order-kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - ms-order-kafka
    ports:
      - "19000:9000"
    networks:
      - order-management-network
    environment:
      KAFKA_BROKERCONNECT: ms-order-kafka:29092

  ms-order-postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    networks:
      - order-management-network
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  ms-order-api:
    image: 'ms-order:latest'
    build: ./ms-order
    networks:
      - order-management-network
    depends_on:
      - ms-order-postgres
      - ms-order-kafdrop
    ports:
      - "8091:8091"
    environment:
      - "SPRING_PROFILES_ACTIVE=prd"

  #################################################################################################################

  ms-payment-processor-api:
    image: 'ms-payment-processor:latest'
    build: ./ms-payment-processor
    networks:
      - order-management-network
    ports:
      - "9090:9090"

networks:
  order-management-network:
    driver: bridge