name: ms-product

services:
    postgres:
      image: postgres:15
      container_name: postgres
      environment:
        POSTGRES_DB: ms-product-dbase
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5415:5432"
      networks:
        - ms-product-network

networks:
  ms-product-network:
    driver: bridge