spring:
  sql:
    init:
      mode: always

  application:
    name: ms-product

  datasource:
    url: jdbc:postgresql://localhost:5415/ms-product-dbase
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      minimum-idle: 5 # Configuração recomendada para pool mínimo
      idle-timeout: 600000 # Tempo máximo que uma conexão pode ficar ociosa
      max-lifetime: 1800000 # Tempo máximo de vida de uma conexão no pool

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  transaction:
    management:
      enabled: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always


server:
  port: 8093

logging:
  level:
    root: INFO
    hibernate: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.datasource.DriverManagerDataSource: TRACE

directory:
  pending: ms-product/src/main/resources/imports/pending
  finished: ms-product/src/main/resources/imports/finished
  waiting: ms-product/src/main/resources/imports/waiting

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
