spring:
  sql:
    init:
      mode: always
  application:
    name: ms-product
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testdb
    username: root
    password: root
  batch:
    job:
      enabled: false


  h2:
    console:
      enabled: true

  jpa:
    show: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

server:
  port: 8092

logging:
  level:
    root: INFO


directory:
  watch: /home/lobaoff/Desktop/repositories/order-management-tc-fase-4/ms-product/src/main/resources/imports/pending
