spring:
  sql:
    init:
      mode: always
  application:
    name: ms-product
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  profiles:
    active: test

  batch:
    job:
      enabled: false
    initialize-schema: always

  transaction:
    management:
      enabled: true

  h2:
    console:
      enabled: true

server:
  port: 8093

logging:
  level:
    root: INFO
    hibernate: TRACE
    org.springframework.transaction: DEBUG

directory:
  pending: ms-product/src/test/resources/pending
  finished: ms-product/src/test/resources/finished
  waiting: ms-product/src/test/resources/waiting

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
