name: ms-customer

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    networks:
      - customer-network
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: customer_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
networks:
  customer-network:
    driver: bridge