services:
  postgres_shipping:
    image: postgres:15
    container_name: postgres_shipping
    environment:
      POSTGRES_DB: ms-shipping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5420:5432"
  ms-shipping:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mysql
    networks:
        - ms-shipping-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-shipping-db:5420/ms-shipping
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
networks:
  ms-shipping-network:
    driver: bridge
volumes:
    mysql-data:
        driver: local